on:
  push:
    branches:
      - master
      - staging_2_test_and_will_delete
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          default-branch: staging_2_test_and_will_delete
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
